package org.adaway.model.root;

import static org.adaway.db.entity.HostsSource.USER_SOURCE_ID;
import static org.adaway.db.entity.HostsSource.USER_SOURCE_URL;
import static org.adaway.db.entity.ListType.BLOCKED;
import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeTrue;

import android.content.Context;
import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.Room;
import androidx.sqlite.db.SupportSQLiteDatabase;
import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import com.topjohnwu.superuser.Shell;

import org.adaway.db.AppDatabase;
import org.adaway.db.entity.HostListItem;
import org.adaway.db.entity.HostsSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.lang.reflect.Field;

@RunWith(AndroidJUnit4.class)
public class RootModelApplyInstrumentedTest {
    private static final String ROOT_APPLY_SMOKE_ARG = "rootHostsApplySmoke";
    private static final String TEST_DATABASE_NAME = "root-model-apply-smoke.db";
    private static final String HOSTS_BACKUP_PATH =
            "/data/local/tmp/adaway-rootmodel-hosts.before";
    private static final String SMOKE_HOST = "codex-rootmodel-apply.local";

    private Context context;
    private AppDatabase database;
    private AppDatabase previousDatabase;
    private boolean restoreHostsFile;

    @Before
    public void setUp() throws Exception {
        assumeTrue("Root hosts apply smoke is opt-in only.", isRootApplySmokeEnabled());

        this.context = ApplicationProvider.getApplicationContext();
        assertRootShellAvailable();
        backupSystemHostsFile();

        this.context.deleteDatabase(TEST_DATABASE_NAME);
        this.database = Room.databaseBuilder(this.context, AppDatabase.class, TEST_DATABASE_NAME)
                .allowMainThreadQueries()
                .build();
        initializeDatabase(this.database.getOpenHelper().getWritableDatabase());
        seedBlockedHost();
        this.previousDatabase = swapAppDatabaseSingleton(this.database);
    }

    @After
    public void tearDown() throws Exception {
        try {
            if (this.restoreHostsFile) {
                restoreSystemHostsFile();
            }
        } finally {
            if (this.previousDatabase != null) {
                swapAppDatabaseSingleton(this.previousDatabase);
            }
            if (this.database != null) {
                this.database.close();
            }
            if (this.context != null) {
                this.context.deleteDatabase(TEST_DATABASE_NAME);
                this.context.deleteFile("hosts");
            }
        }
    }

    @Test
    public void rootModelApplyWritesGeneratedHostsFileToWritableSystem() throws Exception {
        new RootModel(this.context).apply();

        Shell.Result hostsResult = Shell.cmd("cat /system/etc/hosts").exec();
        assertShellSuccess("read applied hosts", hostsResult);
        String hostsFile = String.join("\n", hostsResult.getOut());

        assertTrue("RootModel.apply should write the generated AdAway header.",
                hostsFile.contains("# This hosts file has been generated by AdAway on:"));
        assertTrue("RootModel.apply should write the seeded blocked host.",
                hostsFile.contains("127.0.0.1 " + SMOKE_HOST));
        System.out.println("RootModelApplySmoke host=" + SMOKE_HOST
                + " lines=" + hostsResult.getOut().size());
    }

    private static boolean isRootApplySmokeEnabled() {
        Bundle arguments = InstrumentationRegistry.getArguments();
        return "true".equals(arguments.getString(ROOT_APPLY_SMOKE_ARG));
    }

    private static void assertRootShellAvailable() {
        Shell.getShell();
        Shell.Result result = Shell.cmd("id").exec();
        assertShellSuccess("root shell id", result);
        String id = String.join("\n", result.getOut());
        assertTrue("RootModel.apply smoke requires a root shell, got: " + id,
                id.contains("uid=0"));
    }

    private void backupSystemHostsFile() {
        Shell.Result result = Shell.cmd(
                "cp /system/etc/hosts " + HOSTS_BACKUP_PATH,
                "sha256sum " + HOSTS_BACKUP_PATH).exec();
        assertShellSuccess("backup system hosts", result);
        this.restoreHostsFile = true;
        System.out.println("RootModelApplySmoke backup=" + result.getOut());
    }

    private static void restoreSystemHostsFile() {
        Shell.Result result = Shell.cmd(
                "cp " + HOSTS_BACKUP_PATH + " /system/etc/hosts",
                "chmod 644 /system/etc/hosts",
                "chown 0:0 /system/etc/hosts",
                "sha256sum /system/etc/hosts").exec();
        assertShellSuccess("restore system hosts", result);
        System.out.println("RootModelApplySmoke restore=" + result.getOut());
    }

    private void seedBlockedHost() {
        HostsSource source = new HostsSource();
        source.setId(USER_SOURCE_ID);
        source.setLabel("Root apply smoke");
        source.setUrl(USER_SOURCE_URL);
        source.setEnabled(true);
        this.database.hostsSourceDao().insert(source);

        HostListItem item = new HostListItem();
        item.setType(BLOCKED);
        item.setHost(SMOKE_HOST);
        item.setEnabled(true);
        item.setSourceId(USER_SOURCE_ID);
        this.database.hostsListItemDao().insert(item);
    }

    private static void initializeDatabase(@NonNull SupportSQLiteDatabase writableDatabase) {
        AppDatabase.optimizeCreatedDatabaseStorage(writableDatabase);
        writableDatabase.execSQL("INSERT OR IGNORE INTO hosts_meta "
                + "(id, active_generation) VALUES (0, 0)");
        writableDatabase.execSQL("INSERT OR IGNORE INTO hosts_stats "
                + "(id, blocked_count, blocked_exact_count, allowed_count, redirected_count, "
                + "active_rule_count, root_export_materialized, root_export_stage_materialized) "
                + "VALUES (0, 0, 0, 0, 0, 0, 0, 0)");
    }

    private static void assertShellSuccess(String label, Shell.Result result) {
        assertTrue(label + " failed code=" + result.getCode()
                        + " out=" + result.getOut() + " err=" + result.getErr(),
                result.isSuccess());
    }

    private static AppDatabase swapAppDatabaseSingleton(@Nullable AppDatabase database)
            throws Exception {
        Field field = AppDatabase.class.getDeclaredField("instance");
        field.setAccessible(true);
        AppDatabase previous = (AppDatabase) field.get(null);
        field.set(null, database);
        return previous;
    }
}
